Dala 49 euro dat submodule
d-fine/datalandEDC pull request #6
Opened 2022-05-06 13:54 UTC by SiegfriedSobkowiak

# Pull Request DALA 49
`Integration von EuroDaT`
## Things to do during Peer Review
Please check all boxes before the Pull Request is merged. In case you skip a box, describe in the PRs description (that means: here) why the check is skipped.
- [x] The Github Actions (including Sonarqube Gateway and Lint Checks) are green. This is enforced by Github.
- [ ] A peer-review has been executed
  - [ ] The code has been manually inspected by someone who did not implement the feature
  - [ ] The new feature was observed "in running software"
- [ ] The PR actually implements what is described in the JIRA-Issue
- [ ] At least one E2E Test exists testing the new feature
- [ ] Documentation is updated as required
- [ ] The automated deployment is updated if required
- [ ] The new version is deployed to preview using this branch
  - [ ] It's verified that this version actually is the one deployed (check actuator/info for branch name and commit id!)
  - [ ] The new feature is manually used/tested/observed on preview
- [ ] There is at least one picture for each story, which was created before coding has started

2022-05-06 14:19 UTC, SiegfriedSobkowiak commented on .github/workflows/TemurinBase.yaml
>            java-version: 17
An welcher Stelle werden die base images überhaupt verwendet? Zudem läuft die CI in Java 11 während die docker hier auf Java 17 basieren. Das erscheint mir inkonsistent.

2022-05-06 14:19 UTC, SiegfriedSobkowiak commented on baseDockerfiles/temurinBaseImageDockerfile
> +FROM eclipse-temurin:17.0.3_7-jdk-focal
Das Image wird glaube ich nicht verwendet.

2022-05-06 14:19 UTC, SiegfriedSobkowiak commented on build.gradle.kts
> +        .exclude("**/dataland-eurodat-dummyserver/**")
warum wird der dummy server excluded? Der enthält doch selbst geschriebenen code.

2022-05-06 14:19 UTC, SiegfriedSobkowiak commented on build.gradle.kts
> +val connectorVersion = "0.0.1"
Der gleiche Wert wird auch in den gradle properties gesetzt. Kann man den nicht von da verwenden statt hier nochmal zu definieren?

2022-05-09 05:41 UTC, StephanSinn commented on build.gradle.kts
> +        .exclude("**/dataland-eurodat-dummyserver/**")
war nur vorläufig drin beim wip. ist wieder drin

2022-05-09 05:42 UTC, StephanSinn commented on .github/workflows/TemurinBase.yaml
>            java-version: 17
Guten Punkt, sollten wir in diesem Repo alles auf Java 11 einstellen, wegen der dependencies?

2022-05-09 05:48 UTC, StephanSinn commented on build.gradle.kts
> +        .exclude("**/dataland-eurodat-dummyserver/**")
hier ist der eurodat-dummyserver eingetragen, der gar nicht mehr existiert im repo. wurde entsprechend korrigiert

2022-05-09 06:18 UTC, StephanSinn requested changes

2022-05-09 06:18 UTC, StephanSinn commented on dataland-edc-server/e2etest.sh
> +kill -15 "$edc_server_pid"
Diese file ist sehr lang und complex. Wäre hier vllt ein refactoring hin zu kleineren, maintainable, files angebracht in einem ordner e2etests?

2022-05-09 06:18 UTC, StephanSinn commented on dataland-edc-server/prepare_tunnels_and_do_testcurls.sh
> +echo "Test successfully run. Up- and download took $runtime seconds."
In diesem file sind einige Dinge, die auch in dem file e2etests.sh benutzt werden, dies unterstützt nur den Kommentar bei eben dieser file

2022-05-09 06:18 UTC, StephanSinn commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/api/DatalandInternalEdcApi.kt
> +@OpenAPIDefinition(info = Info(title = "Dataland EDC OpenAPI Spec", version = "1.0.0-SNAPSHOT"))
Soll/muss diese versionsnummer synchron sein mit einer release versions nummer?

2022-05-09 06:18 UTC, StephanSinn commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +    // This is a workaround to enable multiple asset upload even-though EuroDaT supports only the ID 1 (see DALA-146)
Soll der kommentar hier bleiben?

2022-05-09 06:18 UTC, StephanSinn commented on settings.gradle.kts
> +includeBuild("trustee-platform/services/edc") // TODO
Hier ist noch ein TODO

2022-05-09 06:18 UTC, StephanSinn commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +        return if (receivedAssets.containsKey(assetId)) {
Kurze Frage: dies ist der chaching layer, nicht wahr?

2022-05-09 06:29 UTC, SiegfriedSobkowiak commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +        return if (receivedAssets.containsKey(assetId)) {
Ja, richtig.

2022-05-09 06:30 UTC, SiegfriedSobkowiak commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +    // This is a workaround to enable multiple asset upload even-though EuroDaT supports only the ID 1 (see DALA-146)
Ja, als Erinnerung das es noch was zu tun gibt.

2022-05-09 08:41 UTC, emanueldfine commented on build.gradle.kts
> +val connectorVersion = "0.0.1"
Schaue ich mir an

2022-05-09 08:47 UTC, emanueldfine commented on build.gradle.kts
> +val connectorVersion = "0.0.1"
Fixed. Wert wird jetzt von den gradle.properties geholt.

2022-05-09 08:51 UTC, emanueldfine commented on build.gradle.kts
> +val connectorVersion = "0.0.1"
Ich habe gesehen, dass im EuroDaT submodule auch ein paar mal hardcoded `val connectorVersion=0.0.1` vorkommt.
Könnte das zum Problem werden, wenn das im submodule irgendwann auf 0.0.2 springt, wir aber in unseren grade.properties noch 0.0.1 stehen haben?

2022-05-09 08:55 UTC, emanueldfine commented on build.gradle.kts
> +        .exclude("**/node_modules/**")
Ich vermute dass das ein copy-paste Überbleibsel aus dem main-Repo ist.
Meines Erachtens könnte man das hier getrost rausnehmen.

2022-05-09 09:00 UTC, emanueldfine commented on dataland-edc-server/e2etest.sh
> +kill -15 "$edc_server_pid"
Finde ich grundsätzlich richtig.

@SiegfriedSobkowiak sprach vorhin im Call dafür, den Aufwand hier erstmal nicht zu betreiben und es so wie jetzt zu lassen.

Bei mir persönlich ist es so, dass ich schwer einschätzen kann, wie groß die maintenance-Häufigkeit hier in Zukunft sein wird.
Wenn wir den Test sehr oft anpassen müssen, fände ich eine Modularisierung der einzelnen Elemente ganz gut.

2022-05-09 09:01 UTC, emanueldfine commented on dataland-edc-server/prepare_tunnels_and_do_testcurls.sh
> +echo "Test successfully run. Up- and download took $runtime seconds."
Analoge Antwort meinerseits

2022-05-09 09:14 UTC, SiegfriedSobkowiak commented on dataland-edc-server/e2etest.sh
> +kill -15 "$edc_server_pid"
Ja, es ist schon duplizierter code dabei und das ist nie schön. Ich habe es mal geändert. Passt das so besser?

2022-05-09 09:16 UTC, emanueldfine commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/api/DatalandInternalEdcApi.kt
> +@OpenAPIDefinition(info = Info(title = "Dataland EDC OpenAPI Spec", version = "1.0.0-SNAPSHOT"))
Fände ich auch Konsistenzgründen ganz gut.
Du meinst ja sicherlich, dass `version` hier mit `devVersion` im build.gradle.kts übereinstimmen könnte:

![image](https://user-images.githubusercontent.com/99255296/167379202-30da112a-3625-42b0-9431-9f277174f789.png)

Ich widme mich dem mal.

2022-05-09 09:17 UTC, ppuetsch commented on .github/workflows/CI.yaml
> +      - 'closed'
Verstehe ich das richtig, dass wir eine Pipeline für Pull requests laufen lassen, die wir closen?

2022-05-09 09:18 UTC, SiegfriedSobkowiak commented on build.gradle.kts
> +val connectorVersion = "0.0.1"
Wenn es bei EuroDaT ein upgrade gibt müssen wir ohnehin aktiv werden. Aber das sollte EuroDaT bei sich fixen.

2022-05-09 09:20 UTC, ppuetsch commented on .github/workflows/CI.yaml
>            java-version: 17
oben java 11 - hier 17. Das sollte konsistent sein.

2022-05-09 09:22 UTC, SiegfriedSobkowiak commented on .github/workflows/CI.yaml
> +      - 'closed'
Das Problem hier ist das in der alten Einstellung immer 2 Tests parallel laufen wovon aufgrund des Tunnelservers immer einer nicht geht. Die Idee war das ja wegen der push Bedingung eh alle pushes laufen und mit dieser Einstellung sollte nochmal CI laufen wenn der merge geclosed wird. Somit sollten bei allen Ereignissen die CI laufen und nie doppelt.

2022-05-09 09:23 UTC, SiegfriedSobkowiak commented on settings.gradle.kts
> +includeBuild("trustee-platform/services/edc") // TODO
ist entfernt

2022-05-09 09:25 UTC, SiegfriedSobkowiak commented on build.gradle.kts
> +        .exclude("**/node_modules/**")
ist raus

2022-05-09 09:28 UTC, ppuetsch commented on .github/workflows/EDC.yaml
> +        run: ./gradlew :dataland-edc-dummyserver:bootJar :dataland-edc-server:jar --no-daemon --stacktrace
Wo/wie wird denn der EDC-Client veröffentlicht? Sollte das nicht auch am besten in diesem yaml passieren?

2022-05-09 09:29 UTC, emanueldfine commented on settings.gradle.kts
> +includeBuild("trustee-platform/services/edc") // TODO
Ich habe das am 25.04. als TODO getaggt, damit wir in naher Zukunft auf den aktuellesten commit des Submodules gehen.
Ich frage mich aber gerade, ob dann nicht vielleicht alles kaputt geht 😆 .

2022-05-09 09:29 UTC, ppuetsch commented on .github/workflows/EDC.yaml
> +          tags: ${{steps.meta.outputs.tags}}
würde ```
          tags: ghcr.io/d-fine/datalandedc/edcdummyserver:${{env.GITHUB_REF}}
```
nicht das gleiche erreichen, aber ohne dass wir die docker-meta action brauchen?

2022-05-09 09:30 UTC, ppuetsch commented on .github/workflows/EDC.yaml
> +        run: ./gradlew :dataland-edc-dummyserver:bootJar :dataland-edc-server:jar --no-daemon --stacktrace
nevermind. gleiches file, weiter unten.

2022-05-09 09:30 UTC, ppuetsch commented on .github/workflows/EDC.yaml
>            java-version: 17
Version hier konsistent 11? Oder bewusst unterschiedliche Versionen? Dann bitte dokumentieren warum

2022-05-09 09:31 UTC, ppuetsch commented on .github/workflows/EDC.yaml
> +        run: ./gradlew dataland-edc-client:publish --no-daemon --stacktrace
sollen wir das in den job oben integrieren?

2022-05-09 09:32 UTC, ppuetsch commented on .github/workflows/EDC.yaml
> +        run: ./gradlew :dataland-edc-dummyserver:bootJar :dataland-edc-server:jar --no-daemon --stacktrace
Vorschlag: 
```
      - name: Build jars and publish EDC Client
        run: ./gradlew :dataland-edc-dummyserver:bootJar :dataland-edc-server:jar :dataland-edc-client:publish --no-daemon --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: $GITHUB_ACTOR
```

2022-05-09 09:36 UTC, ppuetsch commented on build.gradle.kts
> +val connectorVersion = project.properties["connectorVersion"]
* Lieber `val connectorVersion:String by Project`
* connectorVersion und jacocoVersion an der gleichen Stelle im File definieren

2022-05-09 09:41 UTC, emanueldfine commented on .github/workflows/CI.yaml
> +      - 'closed'
Ursprungsproblem hier war, dass die CI bei jedem commit doppelt gelaufen ist (einmal für den PR und einmal für den Branch).  Das hat unseren e2e-Test gestört, denn der darf ja nie doppelt ausgeführt werden (wegen dem Tunnel-Zeugs).

Dieses `closed` macht, dass die CI für den PR nur läuft, wenn der PR gechlossen wird.

2022-05-09 09:44 UTC, ppuetsch commented on gradle.properties
> +swaggerJaxrs2Version=2.2.0
rsApi und swaggerJaxrs2Version können raus

2022-05-09 09:47 UTC, ppuetsch commented on dataland-edc-dummyserver/src/main/kotlin/org/dataland/edcDummyServer/controller/DummyController.kt
> +    override fun insertData(body: String?): ResponseEntity<Map<String, String>> {
Wir sollten lieber ein Objekt statt einer Map zurückgeben.

2022-05-09 09:47 UTC, emanueldfine commented on .github/workflows/EDC.yaml
> +        run: ./gradlew :dataland-edc-dummyserver:bootJar :dataland-edc-server:jar --no-daemon --stacktrace
Ich denke das passiert ganz unten in einem separatem Job

2022-05-09 09:48 UTC, ppuetsch commented on dataland-edc-dummyserver/src/main/kotlin/org/dataland/edcDummyServer/service/InMemoryDataStore.kt
>      var data = mutableMapOf<String, String>()
Threadsafe vesion benutzen

2022-05-09 10:03 UTC, emanueldfine commented on .github/workflows/EDC.yaml
> +          tags: ${{steps.meta.outputs.tags}}
Laut meiner Recherche würde GITHUB_REF komplett ausschreiben `refs/tags/<tag_name>`.

Würde also `steps.meta.outputs.tags` nicht sauber nur den tag verwenden? Hier bin ich mir trotz Google nicht ganz sicher.

2022-05-09 10:09 UTC, emanueldfine commented on .github/workflows/EDC.yaml
> +        run: ./gradlew :dataland-edc-dummyserver:bootJar :dataland-edc-server:jar --no-daemon --stacktrace
Also dass man die bootJars für Client und Server gesammelt in einem Rutsch baut?   Bringt das einen (Performance-)Vorteil?

Dann könnte man doch eigentlich auch direkt alles in einem job machen (Clients + Server-Images)? Oder bringt das einen Nachteil mit sich?
Es würde zumindest ein paar Zeilen Code sparen.

2022-05-09 10:15 UTC, ppuetsch commented on dataland-edc-server/test/e2etest.sh
> +kill -15 "$edc_server_pid"
-15 ist SIGTERM - das ist der default den kill versendet.

2022-05-09 10:18 UTC, ppuetsch commented on dataland-edc-server/test/test_utility.sh
> +  fi
können wir hier nicht is_edc_server_up verwenden? Vielleicht kann `is_edc_server_up` ja einen Parameter (host-url) bekommen?

2022-05-09 10:19 UTC, ppuetsch commented on dataland-edc-server/test/test_utility.sh
> +  regex="\"([a-f0-9\-]+:[a-f0-9\-]+)\""
warum +? Wir wissen doch genau wie viele stellen wir erwarten?
Also:
``` 
  regex="\"([a-f0-9\-]16:[a-f0-9\-]16)\""
```

2022-05-09 10:19 UTC, ppuetsch commented on dataland-edc-server/test/test_utility.sh
> +  regex="\"([a-f0-9\-]+:[a-f0-9\-]+)\""
mit 16: platzhalter für die richtige zahl ;-)

2022-05-09 10:20 UTC, emanueldfine commented on build.gradle.kts
> +val connectorVersion = project.properties["connectorVersion"]
fixed

2022-05-09 10:25 UTC, emanueldfine commented on gradle.properties
> +swaggerJaxrs2Version=2.2.0
Korrekt, die werden ja nur im Submodule benötigt und daher reicht es aus, dass sie in den dortigen gradle.properties gesetzt werden.
Korrekte Begründung?

Fixed

2022-05-09 10:30 UTC, emanueldfine commented on dataland-edc-dummyserver/src/main/kotlin/org/dataland/edcDummyServer/controller/DummyController.kt
> +    override fun insertData(body: String?): ResponseEntity<Map<String, String>> {
Brechen wir hier nicht gerade immer mehr mit unserem ursprünglichen Plan, nur strings zu EuroDaT zu schicken und zurückzubekommen?

Die Map als return-Objekt anstatt dem String war an dieser Stelle ein expliziter Wunsch von Hamid und Stephan, weil sie das letzte Woche backend-seitig gebraucht haben. Wir sollten mal in der Runde darüber reden.

2022-05-09 10:54 UTC, SiegfriedSobkowiak commented on dataland-edc-server/test/test_utility.sh
> +  regex="\"([a-f0-9\-]+:[a-f0-9\-]+)\""
Aus meiner Sicht ist es einfach nicht wichtig aber wenn man will kann man die regex für die UUID verwenden. Das wäre dann "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}" aber das fühlt sich an wie Kanonen auf Spatzen.

2022-05-09 10:57 UTC, SiegfriedSobkowiak commented on dataland-edc-server/test/test_utility.sh
> +  fi
ja kann man machen. Ich stelle das mal um. Von der Zeilenzahl wird sich aber insgesamt nicht viel ändern.

2022-05-09 11:04 UTC, SiegfriedSobkowiak commented on dataland-edc-server/test/test_utility.sh
> +  fi
ist gemacht, der Hauptvorteil jetzt ist das es nur eine Stelle gibt an der auf die response geprüft wird gibt.

2022-05-09 11:08 UTC, SiegfriedSobkowiak commented on dataland-edc-server/test/e2etest.sh
> +kill -15 "$edc_server_pid"
ja stimmt dann nehme ich das raus

2022-05-09 11:17 UTC, SiegfriedSobkowiak commented on dataland-edc-dummyserver/src/main/kotlin/org/dataland/edcDummyServer/service/InMemoryDataStore.kt
>      var data = mutableMapOf<String, String>()
ersetzt

2022-05-09 11:23 UTC, ppuetsch commented on dataland-edc-server/build.gradle.kts
>   *       Fraunhofer Institute for Software and Systems Engineering - added dependencies
Ich denke, Fraunhofer hat gar kein Copyright an einem File, was wir geschrieben haben.
Auch die Lizenz passt nicht: Apache 2.0.

Den Copyright-Header einfach raus.

2022-05-09 11:24 UTC, ppuetsch commented on dataland-edc-server/build.gradle.kts
>   *       Fraunhofer Institute for Software and Systems Engineering - added dependencies
(überall...)

2022-05-09 11:25 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/api/DatalandInternalEdcApi.kt
> +    fun insertData(data: String): Map <String, String>
Lieber Objekt (Data Class) statt Map.

2022-05-09 11:28 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/models/TrusteeClient.kt
> + * An HTTP client to communicate with the EuroDaT Broker
Vielleicht noch dazu schreiben dass das eine stark vereinfachte Version eines open-api generierten Clients ist.

2022-05-09 11:38 UTC, emanueldfine commented on dataland-edc-server/test/test_utility.sh
> +  regex="\"([a-f0-9\-]+:[a-f0-9\-]+)\""
Ich würde sagen dass wenn etwas zurückkommt, dass zumindest ein paar notwendige - aber nicht hinreichende - Kriterien einer UUID erfüllt, dann sind wir bei diesem Test zufrieden.
Daher fände ich auch die aktuell unpräzisere regex ok.

2022-05-09 11:42 UTC, emanueldfine commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/api/DatalandInternalEdcApi.kt
> +    fun insertData(data: String): Map <String, String>
Auch hier mein Kommentar analog:

Brechen wir hier nicht gerade immer mehr mit unserem ursprünglichen Plan, nur strings zu EuroDaT zu schicken und zurückzubekommen?

Die Map als return-Objekt anstatt dem String war an dieser Stelle ein expliziter Wunsch von Hamid und Stephan, weil sie das letzte Woche backend-seitig gebraucht haben. Daher sollten wir in der Runde darüber reden.

2022-05-09 11:43 UTC, emanueldfine commented on dataland-edc-server/build.gradle.kts
>   *       Fraunhofer Institute for Software and Systems Engineering - added dependencies
Beginne zu fixen

2022-05-09 11:53 UTC, SiegfriedSobkowiak commented on settings.gradle.kts
> +includeBuild("trustee-platform/services/edc") // TODO
Ja wir nehmen immer die gleiche Version des EDC wie EruoDaT.

2022-05-09 11:57 UTC, emanueldfine commented on .github/workflows/CI.yaml
> +        if: always()
Ich fände es praktisch, wenn der e2e-test nur gestartet wird, wenn die steps vorher alle erfolgreich waren.

Dadurch werden nicht-erfolgsversprechende workflow-runs vermieden und es wird "Platz" geschaffen, einen neuen Workflow-Run zu starten, denn es kann ja immer nur einer laufen (wegen dem Tunnel-Zeug im e2e-Test).

2022-05-09 11:58 UTC, emanueldfine commented on .github/workflows/CI.yaml
> +          submodules: recursive
Wieso wird hier eigentlich das submodule mit ausgecheckt für sonar?
Die Inhalte dort sind bzw. sollten doch ohnehin nicht Teil der Analyse sein, oder?

2022-05-09 12:02 UTC, emanueldfine commented on .github/workflows/CI.yaml
> +          submodules: recursive
Frage: Ich würde hier gerne besser verstehen, wieso `recursive` gewählt wurde anstatt einfach `true`.
Aus den Google Ergebnissen wurde ich nicht ganz schlau.

2022-05-09 12:07 UTC, emanueldfine commented on .github/workflows/CI.yaml
> +        run: ./gradlew assemble --no-daemon --stacktrace
Ich frage mich gerade, wieso wir in unseren anderen Repos noch nie diese `--stacktrace` flag genutzt haben, damit wir im Falle von Errors mehr Informationen im Log haben.

2022-05-09 12:09 UTC, emanueldfine commented on .github/workflows/EDC.yaml
> +        run: ./gradlew dataland-edc-client:publish --no-daemon --stacktrace
Vorteil wäre, dass es insgesamt schneller und mit weniger Zeilen Code läuft.

Gäbe es denn Nachteile?  Außer vllt der aktuell besseren Übersicht sehe ich keinen.

2022-05-09 12:11 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +    private val testCredentials = context.getSetting("trustee.credentials", "password")
wenn testCredentials in produktivem Code steht macht mich das ... stutzig.

2022-05-09 12:11 UTC, emanueldfine commented on .github/workflows/TemurinBase.yaml
>            java-version: 17
Aktuell wird es nicht verwendet, aber vllt hat @StephanSinn noch etwas damit vor, denn der CI-Sub-Task ist noch auf "in progress".
Also liegt es an @StephanSinn, es zu löschen oder beizubehalten.
Kannst du dich davon trennen Stephan ?

2022-05-09 12:13 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +    }
Die eine Zeile muss nicht in eine eigene Funktion ausgelagert werden, oder?

2022-05-09 12:14 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +            "eurodat-connector-test",
wieder eine Sache wo "test" in produktivem Code steht...

2022-05-09 12:14 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +            "persistent",
die Magic Strings hier sollten alle ausgelagert werden.

2022-05-09 12:18 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +        context.monitor.debug("Provider request is: ${buildProviderRequest(asset)}")
`        context.monitor.debug("Provider request is: ${buildProviderRequest(asset)}")`
würde ich rausnehmen.
Wenn mans unbedingt braucht, dann auch da loggen, wo man wirklich das ProviderRequest zur eigentlichen benutzung baut - und nicht hier darauf hoffen, dass schon das gleiche aus `buildProviderRequest` rauskommt, wie das, was in `registerAsset` tatsächlich benutzt wird.

2022-05-09 12:19 UTC, emanueldfine commented on build.gradle.kts
> +        exclude("**/trustee-platform/**, **/dataland-eurodat-dummyserver/**, **/dataland-eurodat-client/**")
eurodat-dummyserver und -client gibt es nicht mehr, muss nicht excluded werden

2022-05-09 12:20 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +        val trusteeResponse = trusteeClient.registerAsset(buildProviderRequest(asset))
Ich würde `this.registerAsset` und `trusteeClient.registerAsset` unterschiedlich benennen - sonst verwirrt das.

2022-05-09 12:21 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +     * Methode to make data available for pickup from trustee
`Methoid to...`

2022-05-09 12:22 UTC, SiegfriedSobkowiak commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +    private val testCredentials = context.getSetting("trustee.credentials", "password")
ist raus, war vermutlich ein Überbleibsel vom E2E Test

2022-05-09 12:24 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +        return providedAssets.remove(providerAssetId) ?: "No data with assetId $providerAssetId found."
Gibt es irgendeinen "transfered" status auf den man gehen kann?
An dieser Implementierung ist das Problem: In der Mitte der Übertragung passiert was (connection abort). Der Trustee probierts nochmal - und es ist nix mehr da, wir haben es nämlich schon gelöscht.

2022-05-09 13:07 UTC, ppuetsch commented on build.gradle.kts
> +val connectorVersion = project.properties["connectorVersion"]
top

2022-05-09 13:07 UTC, ppuetsch commented on gradle.properties
> +swaggerJaxrs2Version=2.2.0
ja - genau!

2022-05-09 13:11 UTC, ppuetsch commented on dataland-edc-dummyserver/src/main/kotlin/org/dataland/edcDummyServer/service/InMemoryDataStore.kt
>      var data = mutableMapOf<String, String>()
Im Hauptrepo wird ConcurrentHashMap benutzt. Laut ist für uns beides ok - synchronized ggf. sogar besser. 
In jedem fall sollten wir es konsistent machen.

2022-05-09 13:12 UTC, ppuetsch commented on dataland-edc-server/test/e2etest.sh
> +kill -15 "$edc_server_pid"
ok

2022-05-09 13:13 UTC, ppuetsch commented on dataland-edc-server/test/test_utility.sh
> +  fi
ok

2022-05-09 13:25 UTC, ppuetsch commented on dataland-edc-server/build.gradle.kts
>   *       Fraunhofer Institute for Software and Systems Engineering - added dependencies
ja - klar. perfekt

2022-05-09 13:30 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +    private val testCredentials = context.getSetting("trustee.credentials", "password")
ok

2022-05-09 13:30 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +    private val providedAssets: MutableMap<String, String> = mutableMapOf()
siehe diskussion um ConcurrentHashMap vs. Synchronized

2022-05-09 13:31 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +        return providedAssets.remove(providerAssetId) ?: "No data with assetId $providerAssetId found."
Hat sich erledigt - wir kriegen die Response erst, wenn der Transfer fertig ist.

2022-05-09 13:32 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/controller/DatalandInternalEdcController.kt
> +        return mapOf("dataId" to dataManager.provideAssetToTrustee(data))
Hat sich erledigt - wir kriegen die Response erst, wenn der Transfer fertig ist.

2022-05-09 13:44 UTC, SiegfriedSobkowiak commented on .github/workflows/CI.yaml
> +          submodules: recursive
ja genau das ist der Grund. Ansonsten wird der code nicht komplett ausgecheckt.

2022-05-09 13:46 UTC, SiegfriedSobkowiak commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +            "eurodat-connector-test",
ist jetzt raus

2022-05-09 13:47 UTC, SiegfriedSobkowiak commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +            "persistent",
sind alle in explizite variablen gewandert

2022-05-09 13:48 UTC, SiegfriedSobkowiak commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +        context.monitor.debug("Provider request is: ${buildProviderRequest(asset)}")
das war nur zum debuggen kann aber meiner Meinung nach raus und ist es jetzt auch

2022-05-09 13:49 UTC, SiegfriedSobkowiak commented on build.gradle.kts
> +        exclude("**/trustee-platform/**, **/dataland-eurodat-dummyserver/**, **/dataland-eurodat-client/**")
sind raus

2022-05-09 13:55 UTC, SiegfriedSobkowiak commented on build.gradle.kts
> +            "**/test/**, **/trustee-platform/**, **/extensions/**, **/DummyEdc.kt"
ich nehme es mal raus

2022-05-09 16:01 UTC, ppuetsch commented on .github/workflows/CI.yaml
> +      - 'closed'
aber warum sollte die pipeline laufen, wenn der PR geclosed wird? Closed = nicht gemerged, oder?

2022-05-09 16:04 UTC, ppuetsch commented on .github/workflows/CI.yaml
> +      - 'closed'
Ok - die Doku hilft weiter:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges

"When a pull request merges, the pull request is automatically closed."

Aber reicht nicht das "push" event? Also, läuft die Pipeline für Main dann nicht eh wenn es gemerged wird?

2022-05-09 16:05 UTC, ppuetsch commented on .github/workflows/CI.yaml
>            java-version: 17
ist jetzt 11

2022-05-09 16:06 UTC, ppuetsch commented on .github/workflows/EDC.yaml
>            java-version: 17
ist gelöst.

2022-05-09 16:07 UTC, ppuetsch commented on .github/workflows/EDC.yaml
> +        run: ./gradlew dataland-edc-client:publish --no-daemon --stacktrace
ja dann los

2022-05-09 16:08 UTC, ppuetsch commented on .github/workflows/EDC.yaml
> +        run: ./gradlew :dataland-edc-dummyserver:bootJar :dataland-edc-server:jar --no-daemon --stacktrace
ja - genau!

2022-05-09 16:08 UTC, ppuetsch commented on .github/workflows/EDC.yaml
> +        run: ./gradlew :dataland-edc-dummyserver:bootJar :dataland-edc-server:jar --no-daemon --stacktrace
nur ein job bitte

2022-05-09 16:09 UTC, ppuetsch commented on dataland-edc-dummyserver/src/main/kotlin/org/dataland/edcDummyServer/controller/DummyController.kt
> +    override fun insertData(body: String?): ResponseEntity<Map<String, String>> {
hatten wir drüber geredet: an EuroDaT schicken wir ja immernoch nur einen string. Aber die interne Kommunikation können wir ja explizit machen.

2022-05-09 16:13 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/api/DatalandInternalEdcApi.kt
> +    fun insertData(data: String): Map <String, String>
Bitte bei dem checkHealth Endpoint noch analog verfahren.

2022-05-09 16:15 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/models/TrusteeClient.kt
> + * An HTTP client to communicate with the EuroDaT Broker
hab ich gemacht.

2022-05-09 16:16 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +        context.monitor.debug("Provider request is: ${buildProviderRequest(asset)}")
ok

2022-05-09 16:17 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +        val trusteeResponse = trusteeClient.registerAsset(buildProviderRequest(asset))
ok

2022-05-09 16:17 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +     * Methode to make data available for pickup from trustee
ok

2022-05-10 06:40 UTC, SiegfriedSobkowiak commented on baseDockerfiles/temurinBaseImageDockerfile
> +FROM eclipse-temurin:17.0.3_7-jdk-focal
wurde entfernt

2022-05-10 06:40 UTC, SiegfriedSobkowiak commented on .github/workflows/TemurinBase.yaml
>            java-version: 17
ist alles auf 11 umgestellt

2022-05-10 06:57 UTC, SiegfriedSobkowiak commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +    private val providedAssets: MutableMap<String, String> = mutableMapOf()
geändert in concurrenthashmap

2022-05-10 06:57 UTC, emanueldfine commented on dataland-edc-dummyserver/src/main/kotlin/org/dataland/edcDummyServer/service/InMemoryDataStore.kt
> +        this.data[dataID] = data
Benamung etwas verwirrend mit einmal `data` als Map und einmal `data` als lokale Input-Variable

2022-05-10 06:57 UTC, emanueldfine commented on dataland-edc-dummyserver/src/main/kotlin/org/dataland/edcDummyServer/service/InMemoryDataStore.kt
> +        this.data[dataID] = data
Das "this." könnte dann auch weg

2022-05-10 06:58 UTC, emanueldfine commented on dataland-edc-dummyserver/src/test/kotlin/org/dataland/edcDummyServer/DummyEdcControllerTest.kt
> +        println(body)
Debug statement

2022-05-10 07:00 UTC, emanueldfine commented on dataland-edc-server/build.gradle.kts
> +val connectorVersion: String by project
Zur `val jacocoVersion` oben verschieben analog zum Hauptgradle

2022-05-10 07:01 UTC, emanueldfine commented on dataland-edc-server/build.gradle.kts
> +    implementation(libs.awaitility.kotlin)
Würde nur `libs.awaitility` nicht ausreichen? Oder eben nur das untere.

2022-05-10 07:01 UTC, SiegfriedSobkowiak commented on dataland-edc-dummyserver/src/test/kotlin/org/dataland/edcDummyServer/DummyEdcControllerTest.kt
> +        println(body)
entfernt

2022-05-10 07:04 UTC, SiegfriedSobkowiak commented on .github/workflows/CI.yaml
> +      - 'closed'
Wenn der merge auch als push zählt sollte eigentlich "push: branches: **" reichen, dann wird ja bei jedem der events das wir haben wollen eine CI ausgelöst. Ich mach das mal so.

2022-05-10 07:10 UTC, SiegfriedSobkowiak commented on .github/workflows/EDC.yaml
> +        run: ./gradlew :dataland-edc-dummyserver:bootJar :dataland-edc-server:jar --no-daemon --stacktrace
der zweite job ist in den ersten gemerged

2022-05-10 07:10 UTC, emanueldfine commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +        private val pollInterval = Duration.ofMillis(2000)
@ppuetsch du meintest am Donnerstag, dass 2 Sekunden für `pollInterval` zu hoch seien. Soll ich das zurückstellen auf 100 millis?

2022-05-10 07:10 UTC, SiegfriedSobkowiak commented on .github/workflows/EDC.yaml
> +        run: ./gradlew dataland-edc-client:publish --no-daemon --stacktrace
erledigt (siehe oben)

2022-05-10 07:11 UTC, emanueldfine commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +    private val providedAssets: ConcurrentHashMap<String, String> = ConcurrentHashMap()
Ich war hier nicht dabei. Mich würden die Vorteile der ConcurrentHashMap gegenüber einer MutableMap interessieren.
Anschließend schließe ich diese Conversation

2022-05-10 07:13 UTC, SiegfriedSobkowiak commented on dataland-edc-server/build.gradle.kts
> +val connectorVersion: String by project
erledigt

2022-05-10 07:17 UTC, emanueldfine commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +        val providerAssetId = UUID.randomUUID().toString()
Irgendwo habe ich `val datalandAssetId` statt `providerAssetId`. Fand ich gut, denn wir sind ja der Provider.
Vllt hier dann auch in der Funktion?

2022-05-10 07:20 UTC, emanueldfine commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +    private fun retrieveAssetFromTrustee(assetId: String, contractDefinitionId: String): String {
Genereller Gedanke, weil es mir hier im DataManager generell aufgefallen ist:

In der API war das wording `eurodatAssetId` und `datalandAssetId`, um beides zu unterscheiden.

Wie seht ihr das, auch hier im DataManager diese Differenzierung im Wording vorzunehmen?

2022-05-10 07:22 UTC, emanueldfine commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +        return receivedAssets[assetId] ?: "Data not found"
Wie wäre es mit `Data with eurodatAssetId $assetId not found.`

2022-05-10 07:23 UTC, emanueldfine commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +    }
zusätzlich vllt ein log mit `Asset from trustee with eurodatAssetId $assetId was received and stored.`

2022-05-10 07:27 UTC, SiegfriedSobkowiak commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +        val providerAssetId = UUID.randomUUID().toString()
wir sind tatsächlich beides, je nach use case aber ich habe es mal auf datalandAssetId geändert

2022-05-10 07:27 UTC, emanueldfine commented on dataland-edc-server/test/test_utility.sh
> +  if ! curl -f -X 'GET' "${TRUSTEE_URI}/ids/description" -H 'accept: application/json' >/dev/null 2>&1; then
Ich fänds gut wenn $TRUSTEE_URI oben in eine Variable geschrieben wird, und diese dann hier verwendet wird.

Dann hat man oben alle Variablen die im Skript vorkommen an einer Stelle, falls später Änderungen notwendig werden.

2022-05-10 07:28 UTC, SiegfriedSobkowiak commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +    private val providedAssets: ConcurrentHashMap<String, String> = ConcurrentHashMap()
die setzt zum Beispiel kein komplettes lock auf das gesamte Objekt sonder nur auf Teile, hat dadurch weniger overhead und bessere Performance

2022-05-10 07:32 UTC, SiegfriedSobkowiak commented on dataland-edc-dummyserver/src/main/kotlin/org/dataland/edcDummyServer/service/InMemoryDataStore.kt
> +        this.data[dataID] = data
habe es in storedData geändert

2022-05-10 07:33 UTC, SiegfriedSobkowiak commented on dataland-edc-server/test/test_utility.sh
> +  cd ../../ || exit
falls der Wechsel des directory fehlschlägt soll es einen exit geben, weil sonst die nächste Zeile keinen Sinn ergeben würde

2022-05-10 07:36 UTC, SiegfriedSobkowiak commented on dataland-edc-server/test/test_utility.sh
> +  if ! curl -f -X 'GET' "${TRUSTEE_URI}/ids/description" -H 'accept: application/json' >/dev/null 2>&1; then
aber TRUSTEE_URI ist eine Umgebungsvariable, wenn ich die ändern will dann mus die entsprechende Variable geändert werden. Umgebungsvariablen sollten local in Scripten nicht geändert werden.

2022-05-10 07:39 UTC, SiegfriedSobkowiak commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +    }
log hinzugefügt

2022-05-10 07:40 UTC, ppuetsch commented on .github/workflows/CI.yaml
> +      - 'closed'
ist jetzt weg. Thread wird geschlossen.

2022-05-10 07:40 UTC, ppuetsch commented on .github/workflows/EDC.yaml
> +        run: ./gradlew dataland-edc-client:publish --no-daemon --stacktrace
top

2022-05-10 07:40 UTC, ppuetsch commented on .github/workflows/EDC.yaml
> +        run: ./gradlew :dataland-edc-dummyserver:bootJar :dataland-edc-server:jar --no-daemon --stacktrace
top

2022-05-10 07:41 UTC, SiegfriedSobkowiak commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +        return receivedAssets[assetId] ?: "Data not found"
angepasst

2022-05-10 07:43 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +            "persistent",
ok

2022-05-10 07:45 UTC, ppuetsch commented on dataland-edc-server/build.gradle.kts
> +    implementation(libs.awaitility.kotlin)
Nein - das obere ist die eigentliche Funktionalität, und das untere sind Kotlin-Wrapper auf das obere. Wir könnten nur mit dem oberen klarkommen, wäre dann aber weniger schön im Code.

2022-05-10 07:45 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +        private val pollInterval = Duration.ofMillis(2000)
jup

2022-05-10 07:45 UTC, SiegfriedSobkowiak commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +    private fun retrieveAssetFromTrustee(assetId: String, contractDefinitionId: String): String {
eurodat und trustee finde ich beide okay. Wobei trustee eigentlich schöner ist weil es das abstrakte Konzept beschreibt und nicht die spezielle Implementierung.

2022-05-10 07:47 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +    private val providedAssets: ConcurrentHashMap<String, String> = ConcurrentHashMap()
MutableMap ist nicht Threadsafe. Wenn zwei Threads gleichzeitig in eine MutableMap schreiben, passieren schlimme Dinge (z.B. dass nur einer der Schreibvorgänge überlebt - die Map sieht so aus, als wäre einer der Schreibvorgänge gar nicht passiert). 
Das ist im Hauptrepo aufgefallen, als wir beim initialisieren mit so vielen Requests gleichzeitig gekommen sind.

Da das ja aber eine Multithreaded Anwendung ist, sollten wir immer Threadsafe sein.

Und ConcurrentHashMap löst das

2022-05-10 07:53 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +    private fun retrieveAssetFromTrustee(assetId: String, contractDefinitionId: String): String {
klingt top - gerne machen!

2022-05-10 07:54 UTC, SiegfriedSobkowiak commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/api/DatalandInternalEdcApi.kt
> +@OpenAPIDefinition(info = Info(title = "Dataland EDC OpenAPI Spec", version = "1.0.0-SNAPSHOT"))
Das sind hier tatsächlich zwei verschiedene Dinge die API version (die nur wir selber benutzen und damit irrelevant ist) und die version vom Code. Ich würde die API einfach als un-versioned deklarieren und den Rest behandeln wie bisher.

2022-05-10 07:56 UTC, ppuetsch commented on dataland-edc-server/test/test_utility.sh
> +  cd ../../ || exit
|| ist ein Shell-Oder: Wenn der erste Befehl nicht klappt, führt er den zweiten aus. 
Konkret heißt das hier: Wenn das `cd ../../` nicht klappt, verlasse das script (denn dann ergibt alles eh keinen Sinn mehr)

2022-05-10 08:24 UTC, emanueldfine commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/api/DatalandInternalEdcApi.kt
> +@OpenAPIDefinition(info = Info(title = "Dataland EDC OpenAPI Spec", version = "1.0.0-SNAPSHOT"))
@SiegfriedSobkowiak  lass uns mal kurz über diesen Punkt und die technische Realisierung sprechen.

2022-05-10 08:24 UTC, SiegfriedSobkowiak commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +    private fun retrieveAssetFromTrustee(assetId: String, contractDefinitionId: String): String {
ist jetzt vereinheitlicht, es gibt jetzt keine blanken assetIds mehr sondern nur trusteeAssetId oder datalandAssetId

2022-05-10 08:32 UTC, emanueldfine commented on dataland-edc-dummyserver/src/main/kotlin/org/dataland/edcDummyServer/service/InMemoryDataStore.kt
>      var data = mutableMapOf<String, String>()
Habe in der Gruppe für ConcurrentHashMap gestimmt, weil sie keine nulls in keys und values zulässt.
Wenn wir das anders gewährleisten, verschwindet bei mir dieses Argument und somit die Präferenz.

Der "When to use" Teil würde aber ja eher für synchronized sprechen.

Die besseren Performance Werte der ConcurrentHashMap spielen für uns bestimmt keine große Rolle nehme ich an.

2022-05-10 08:33 UTC, emanueldfine commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/api/DatalandInternalEdcApi.kt
> +    fun insertData(data: String): Map <String, String>
Beginne zu bearbeiten

2022-05-10 08:34 UTC, StephanSinn approved these changes

2022-05-10 08:37 UTC, emanueldfine commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/api/DatalandInternalEdcApi.kt
> +@OpenAPIDefinition(info = Info(title = "Dataland EDC OpenAPI Spec", version = "1.0.0-SNAPSHOT"))
Verstanden. Passt für mich

2022-05-10 08:38 UTC, emanueldfine commented on dataland-edc-server/test/test_utility.sh
> +  cd ../../ || exit
Alles klar. Danke euch

2022-05-10 08:44 UTC, emanueldfine commented on dataland-edc-server/test/test_utility.sh
> +  if ! curl -f -X 'GET' "${TRUSTEE_URI}/ids/description" -H 'accept: application/json' >/dev/null 2>&1; then
Ja ich hab mich etwas schlecht ausgedrückt.

Ich meinte eher folgendes Szenario:

- Das Skript läuft nicht
- Man fragt sich ob es vllt an einer Umgebungsvariablen mit falschem/veraltetem oder fehlendem Wert liegen könnte
- Man möchte möglichst schnell alle Umgebungsvariablen sehen, die in dem Skript genutzt werden
=> Man sieht aktuell alle verwendeten Umgebungsvariablen an einer Stelle, außer TRUSTEE_URI

Daher könnte man oben quasi noch ergänzen:
`export trustee_uri=$TRUSTEE_URI`

2022-05-10 09:00 UTC, emanueldfine commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +        return receivedAssets[assetId] ?: "Data not found"
Hat mich auf einen weiteren Naming-Gedanken gebracht:

Beim Durchlesen des DataManagers ist mir aufgefallen, dass wir teils etwas holprig sind in der Unterscheidung zwischen `data` und `asset`.
Aber ehrlich gesagt finde ich es schwierig, dafür eine gute Lösung/Konvention zu definieren.

Z.B. lassen die Maps `receivedAssets` und `providedAssets` den Leser erwarten, da stecken Asset Objekte drin.
Aber eigentlich sind es nur Mappings von assetIds auf Daten (Strings).

2022-05-10 09:10 UTC, emanueldfine commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/api/DatalandInternalEdcApi.kt
> +    fun insertData(data: String): Map <String, String>
Fixed. Health Ednpoint returnt jetzt ein Objekt `CheckHealthResponse`

2022-05-10 09:16 UTC, emanueldfine commented on build.gradle.kts
> +            "**/test/**, **/trustee-platform/**, **/extensions/**, **/DummyEdc.kt"
Warte auf einen run mit unveränderter Coverage. Dann schließe ich die conversation

2022-05-10 09:17 UTC, emanueldfine commented on dataland-edc-server/build.gradle.kts
> +    implementation(libs.awaitility.kotlin)
Alles klar.

2022-05-10 09:23 UTC, emanueldfine commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +        private val pollInterval = Duration.ofMillis(2000)
fixed

2022-05-10 09:27 UTC, ppuetsch commented on .github/workflows/EDC.yaml
> +          tags: ${{steps.meta.outputs.tags}}
so wie es jetzt ist passt es.

2022-05-10 09:28 UTC, emanueldfine commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +    private fun retrieveAssetFromTrustee(assetId: String, contractDefinitionId: String): String {
Passt im edc-server jetzt.

Nur im edc-dummy-server gibt es noch eine blanke assetId. Die würde ich jetzt zu `trusteeAssetId` umbenennen, weil sie quasi die assetId simuliert, unter der das echte EuroDaT die Daten speichern würde.

2022-05-10 09:34 UTC, ppuetsch commented on dataland-edc-dummyserver/src/main/kotlin/org/dataland/edcDummyServer/service/InMemoryDataStore.kt
>      var data = mutableMapOf<String, String>()
ok

2022-05-10 09:35 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/api/DatalandInternalEdcApi.kt
> +    fun insertData(data: String): Map <String, String>
ok

2022-05-10 09:37 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +        private val pollInterval = Duration.ofMillis(2000)
ok

2022-05-10 09:39 UTC, ppuetsch commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +    private fun retrieveAssetFromTrustee(assetId: String, contractDefinitionId: String): String {
ok

2022-05-10 09:59 UTC, emanueldfine commented on build.gradle.kts
> +            "**/test/**, **/trustee-platform/**, **/extensions/**, **/DummyEdc.kt"
Lief gerade durch. Passt also

2022-05-10 10:32 UTC, SiegfriedSobkowiak commented on dataland-edc-server/test/test_utility.sh
> +  if ! curl -f -X 'GET' "${TRUSTEE_URI}/ids/description" -H 'accept: application/json' >/dev/null 2>&1; then
dann sollte man aber schon ${TRUSTEE_URI}/ids/description als neue Variable nehmen das ergibt dann mehr Sinn

2022-05-10 10:35 UTC, SiegfriedSobkowiak commented on dataland-edc-server/test/test_utility.sh
> +  if ! curl -f -X 'GET' "${TRUSTEE_URI}/ids/description" -H 'accept: application/json' >/dev/null 2>&1; then
ist geändert

2022-05-10 10:36 UTC, SiegfriedSobkowiak commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +        return receivedAssets[assetId] ?: "Data not found"
Ja, wir reden eher von Daten und EuroDaT spricht immer von assets.

2022-05-10 10:38 UTC, emanueldfine commented on dataland-edc-server/build.gradle.kts
> +}*/
Kommentar kann raus sobald validiert, dass alles klappt.

2022-05-10 10:39 UTC, SiegfriedSobkowiak commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +        return receivedAssets[assetId] ?: "Data not found"
Aus meiner Sicht können wir es erstmal so lassen. Wir werden ja demnächst nochmal alles überarbeiten müssen sobald es keine EuroDaT REST mehr gibt. In diesem Zusammenhang könnte man das wording noch mal überdenken.

2022-05-10 11:39 UTC, emanueldfine commented on dataland-edc-server/src/main/kotlin/org/dataland/edc/server/service/DataManager.kt
> +        return receivedAssets[assetId] ?: "Data not found"
Alles klar. Finde ich dann erstmal ok

2022-05-10 11:42 UTC, emanueldfine commented on dataland-edc-server/test/test_utility.sh
> +  if ! curl -f -X 'GET' "${TRUSTEE_URI}/ids/description" -H 'accept: application/json' >/dev/null 2>&1; then
Ok.  Könnten wir bei den anderen Endpunkten auch machen, aber ist auch so ok. Wird sich ja sowieso auch ändern.

2022-05-12 11:02 UTC, merged